### ISSUE TITLE
Is there a way to switch dotnet versions?

### ISSUE THREAD

**Issue by sp-adrian-simbulan** [dn-vm/dnvm#143]
I've this tool to install multiple versions of dotnet locally. I was wondering what the command was to switch between them?

**Comment by agocke** [comment]
The dotnet host "multiplexes" across multiple versions by default. You can either use a [global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to lock a particular directory to one version, if that's what you want, or you can just let it choose the newest SDK.

You can also use dnvm to install to multiple directories if you want to have them fully separated. The `-s` command to `install` will do that. Then you can use `dnvm select` to switch between those directories.

**Comment by agocke** [comment]
Hm, I haven't tried single letters as dir names -- this might be a bug

**Comment by ahmet-cetinkaya** [comment]
I tried with a word. But it gives the same error:

```
> dnvm list     
dnvm 0.9.6 0aabd741

DNVM_HOME: /home/ac/.local/share/dnvm

Installed SDKs:

┌───┬─────────┬─────────┬──────────┐
│   │ Version │ Channel │ Location │
├───┼─────────┼─────────┼──────────┤
│   │ 9.0.302 │ latest  │ nine     │
│   │ 8.0.412 │         │ eight    │
└───┴─────────┴─────────┴──────────┘

Tracked channels:

 • latest

> dnvm select eight
dnvm 0.9.6 0aabd741


Error: Invalid SDK directory name: eight

Valid SDK directory names:
  dn

> dnvm select nine 
dnvm 0.9.6 0aabd741


Error: Invalid SDK directory name: nine

Valid SDK directory names:
  dn
```

**Comment by agocke** [comment]
Ah, found the problem. The directory doesn't show up when there's nothing `tracked` in the channel. I'll have a fix shortly.

**Comment by agocke** [comment]
Bug here: https://github.com/dn-vm/dnvm/issues/261
