### ISSUE TITLE
Preview vs preview breaks select

### ISSUE THREAD

**Issue by 333fred** [dn-vm/dnvm#82]
There are some casing issues with `Preview` vs `preview` in `dnvm select`: The former breaks, while the latter works:

![image](https://github.com/dn-vm/dnvm/assets/2371880/8b74daf0-5ff0-4724-865a-43e60087b6cf)

**Comment by agocke** [comment]
I'll implement checking for this, so `select` only accepts valid inputs, and provides a list of the available ones. Would you prefer doing a case-insensitive match?

**Comment by 333fred** [comment]
I'm perfectly fine with it only accepting correct casing, everything else on Linux works that way. The docs everywhere say `Preview`, but that apparently installed to a lower-case `preview` directory.
